language: python
python:
  - "2.7"
  - "3.5"

#compiler:
#  - g++
#  - clang++
#  - gcc-4.7
#  - gcc-4.9
#  - clang-3.7
#  - clang-3.8
#  - clang-nightly
#  - gcc-5.3
#  - gcc-nightly

before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - export PATH="$HOME/miniconda/bin:$PATH"
  - df -h
  - date
  - pwd
  - uname -a
  - python -V
  - which g++
  - g++ --version
  - export CXX="g++"
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

# command to install dependencies
install:
  - export CXX=g++
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - ls $(dirname $(which g++))/g++*
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - echo "install"
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION swig=3.0.8 pandas numpy
  - source activate test-environment
  - cd python
  - python setup.py build install

# command to run tests
script: nosetests tests/test_paratext.py
